import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { cookieToInitialState } from 'wagmi';
import { WagmiConfig } from '@/lib/config';
import { headers } from 'next/headers';
import { CustomWagmiProvider } from '@/providers/wagmi-provider';
import { CustomNav } from '@/components/custom/nav';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headerList = await headers();
    const cookieHeader = headerList.get('cookie');
    const initalState = cookieToInitialState(WagmiConfig(), cookieHeader);

    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable} relative antialiased w-[500px] mx-auto`}>
                <CustomWagmiProvider initialState={initalState}>
                    <CustomNav />
                    {children}
                </CustomWagmiProvider>
            </body>
        </html>
    );
}
